Traceback (most recent call last):
  File "/Users/kifumi/local/qiskit_0441_2/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/kifumi/local/qiskit_0441_2/lib/python3.9/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/kifumi/local/qiskit_0441_2/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 166, in wrapped
    return loop.run_until_complete(inner)
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/Users/kifumi/local/qiskit_0441_2/lib/python3.9/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/Users/kifumi/local/qiskit_0441_2/lib/python3.9/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/kifumi/local/qiskit_0441_2/lib/python3.9/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import math
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec

# Qiskit
from qiskit_machine_learning.algorithms import QGAN

from qiskit import BasicAer, ClassicalRegister, QuantumCircuit, execute
from qiskit.circuit.library import TwoLocal
from qiskit.quantum_info import random_statevector
from qiskit_finance.circuit.library.probability_distributions import UniformDistribution, NormalDistribution
from qiskit.utils import QuantumInstance # qiskit >0.25

from qiskit_machine_learning.algorithms.distribution_learners import NumPyDiscriminator, PyTorchDiscriminator  # qiskit >0.25
from qiskit_machine_learning.datasets.dataset_helper import discretize_and_truncate # qiskit >0.25


# pytorch dataset
import torchvision.transforms as transforms
from torch.utils.data import Dataset, DataLoader
import torch
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [0;32mIn[3], line 9[0m
[1;32m      6[0m [38;5;28;01mimport[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mgridspec[39;00m [38;5;28;01mas[39;00m [38;5;21;01mgridspec[39;00m
[1;32m      8[0m [38;5;66;03m# Qiskit[39;00m
[0;32m----> 9[0m [38;5;28;01mfrom[39;00m [38;5;21;01mqiskit_machine_learning[39;00m[38;5;21;01m.[39;00m[38;5;21;01malgorithms[39;00m [38;5;28;01mimport[39;00m QGAN
[1;32m     11[0m [38;5;28;01mfrom[39;00m [38;5;21;01mqiskit[39;00m [38;5;28;01mimport[39;00m BasicAer, ClassicalRegister, QuantumCircuit, execute
[1;32m     12[0m [38;5;28;01mfrom[39;00m [38;5;21;01mqiskit[39;00m[38;5;21;01m.[39;00m[38;5;21;01mcircuit[39;00m[38;5;21;01m.[39;00m[38;5;21;01mlibrary[39;00m [38;5;28;01mimport[39;00m TwoLocal

[0;31mModuleNotFoundError[0m: No module named 'qiskit_machine_learning'

